### ISSUE TITLE
Jenkinsfile main pipeline required changes

### ISSUE THREAD

**Issue by chvalean** [LIS/lis-pipeline#476]
This is for the Azure kernel, please include the below changes:

1. run P0 to P3 - all priorities.
2. exclude rdma/infiniband functional tests - agreed internally with Sasha/Ju.
3. run on specialized nodes the nvme and sriov areas - for Hyper-V.
[More items to be added, but mostly same as in the upstream pipeline should be carried over]

@lizzha and @juhlee-microsoft for ack.

**Comment by LiliDeng** [comment]
@chvalean Is this stage still needed? https://github.com/LIS/lis-pipeline/blob/master/Jenkinsfile#L504
